/**
 * Demo/test data for Rex Software integration.
 * Realistic Australian property listings that mimic the Rex API response format.
 * Rex uses a different schema structure than AgentBox — these match Rex's expected fields.
 */

export const DEMO_LISTINGS = [
  {
    id: 'rex-demo-001',
    type: 'residential_sale',
    property_category: 'House',
    system_status: 'current',
    headline: 'Stunning Harbour Views from Elevated Position',
    description: 'Commanding breathtaking harbour views from its elevated position, this beautifully updated 4-bedroom residence offers the ultimate in coastal living. Features include a gourmet kitchen with marble benchtops, multiple living zones, and an infinity-edge pool overlooking the harbour.',
    property: {
      adr_street_number: '18',
      adr_street_name: 'Marine Parade',
      adr_suburb_or_town: 'Mosman',
      adr_state_or_region: 'NSW',
      adr_postcode: '2088',
      adr_unit_number: null,
      adr_latitude: -33.8282,
      adr_longitude: 151.2443,
    },
    price_advertise_as: '$4,850,000',
    price_match: 4850000,
    attr_bedrooms: 4,
    attr_bathrooms: 3,
    attr_garages: 2,
    attr_land_area: 720,
    attr_land_area_unit: 'sqm',
    features: ['Pool', 'Air Conditioning', 'Double Garage', 'Harbour Views', 'Home Theatre'],
    images: [
      { uri: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop' },
      { uri: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop' },
      { uri: 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=600&fit=crop' },
    ],
  },
  {
    id: 'rex-demo-002',
    type: 'residential_sale',
    property_category: 'Apartment',
    system_status: 'current',
    headline: 'Designer Apartment in Teneriffe Woolstore',
    description: 'Set within a beautifully converted heritage woolstore, this stunning two-bedroom apartment blends original industrial character with contemporary luxury. Soaring 4m ceilings, exposed brick, polished timber floors, and a private courtyard create an exceptional urban retreat.',
    property: {
      adr_street_number: '34',
      adr_street_name: 'Vernon Terrace',
      adr_suburb_or_town: 'Teneriffe',
      adr_state_or_region: 'QLD',
      adr_postcode: '4005',
      adr_unit_number: '12',
      adr_latitude: -27.4545,
      adr_longitude: 153.0453,
    },
    price_advertise_as: '$895,000',
    price_match: 895000,
    attr_bedrooms: 2,
    attr_bathrooms: 2,
    attr_garages: 1,
    attr_land_area: null,
    attr_land_area_unit: null,
    features: ['Air Conditioning', 'Secure Parking', 'Intercom', 'Heritage Building'],
    images: [
      { uri: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop' },
      { uri: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop' },
    ],
  },
  {
    id: 'rex-demo-003',
    type: 'residential_sale',
    property_category: 'Townhouse',
    system_status: 'current',
    headline: 'Architect-Designed Terrace in Fitzroy',
    description: 'A masterpiece of modern design behind a heritage facade. This three-storey terrace home features soaring void spaces, a cantilevered staircase, hydronic heating throughout, and a rooftop terrace with city skyline views. Walk to Brunswick Street cafes.',
    property: {
      adr_street_number: '22',
      adr_street_name: 'Napier Street',
      adr_suburb_or_town: 'Fitzroy',
      adr_state_or_region: 'VIC',
      adr_postcode: '3065',
      adr_unit_number: null,
      adr_latitude: -37.7982,
      adr_longitude: 144.9780,
    },
    price_advertise_as: '$1,650,000',
    price_match: 1650000,
    attr_bedrooms: 3,
    attr_bathrooms: 2,
    attr_garages: 1,
    attr_land_area: 145,
    attr_land_area_unit: 'sqm',
    features: ['Hydronic Heating', 'Rooftop Terrace', 'Heritage Facade', 'City Views'],
    images: [
      { uri: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop' },
      { uri: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop' },
    ],
  },
  {
    id: 'rex-demo-004',
    type: 'residential_sale',
    property_category: 'House',
    system_status: 'current',
    headline: 'Iconic Queenslander with Hinterland Outlook',
    description: 'This meticulously restored 1920s Queenslander sits on a sprawling 1,100sqm block with panoramic hinterland views. Period details include VJ walls, fretwork, and wraparound verandahs. The modern extension adds a chef\'s kitchen, media room, and resort-style pool area.',
    property: {
      adr_street_number: '56',
      adr_street_name: 'Dobell Drive',
      adr_suburb_or_town: 'Currumbin Valley',
      adr_state_or_region: 'QLD',
      adr_postcode: '4223',
      adr_unit_number: null,
      adr_latitude: -28.1672,
      adr_longitude: 153.4584,
    },
    price_advertise_as: '$1,995,000',
    price_match: 1995000,
    attr_bedrooms: 5,
    attr_bathrooms: 3,
    attr_garages: 2,
    attr_land_area: 1100,
    attr_land_area_unit: 'sqm',
    features: ['Pool', 'Air Conditioning', 'Double Garage', 'Hinterland Views', 'Media Room'],
    images: [
      { uri: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=600&fit=crop' },
      { uri: 'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800&h=600&fit=crop' },
      { uri: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop' },
    ],
  },
  {
    id: 'rex-demo-005',
    type: 'residential_sale',
    property_category: 'Villa',
    system_status: 'current',
    headline: 'Sun-Filled Villa in Quiet Cul-de-sac',
    description: 'Perfect for downsizers or first home buyers, this immaculate villa offers easy single-level living in a peaceful complex. North-facing living areas, renovated kitchen with stone benchtops, private courtyard garden, and lock-up garage. Walk to station and shops.',
    property: {
      adr_street_number: '5/12',
      adr_street_name: 'Carrington Road',
      adr_suburb_or_town: 'Castle Hill',
      adr_state_or_region: 'NSW',
      adr_postcode: '2154',
      adr_unit_number: '5',
      adr_latitude: -33.7310,
      adr_longitude: 151.0012,
    },
    price_advertise_as: '$920,000',
    price_match: 920000,
    attr_bedrooms: 3,
    attr_bathrooms: 1,
    attr_garages: 1,
    attr_land_area: 250,
    attr_land_area_unit: 'sqm',
    features: ['Air Conditioning', 'Garage', 'Courtyard', 'Walk to Station'],
    images: [
      { uri: 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&h=600&fit=crop' },
      { uri: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop' },
    ],
  },
  {
    id: 'rex-demo-006',
    type: 'residential_sale',
    property_category: 'House',
    system_status: 'current',
    headline: 'Grand Estate on Toorak\'s Golden Mile',
    description: 'This magnificent double-storey residence on Toorak\'s most prestigious boulevard offers over 600sqm of living space. Six bedrooms, formal and informal living areas, a temperature-controlled wine cellar, home gym, and manicured grounds with heated pool and tennis court.',
    property: {
      adr_street_number: '9',
      adr_street_name: 'St Georges Road',
      adr_suburb_or_town: 'Toorak',
      adr_state_or_region: 'VIC',
      adr_postcode: '3142',
      adr_unit_number: null,
      adr_latitude: -37.8412,
      adr_longitude: 145.0098,
    },
    price_advertise_as: 'Expressions of Interest',
    price_match: 8500000,
    attr_bedrooms: 6,
    attr_bathrooms: 5,
    attr_garages: 4,
    attr_land_area: 1450,
    attr_land_area_unit: 'sqm',
    features: ['Pool', 'Tennis Court', 'Wine Cellar', 'Home Gym', 'Air Conditioning', 'Alarm System'],
    images: [
      { uri: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop' },
      { uri: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop' },
      { uri: 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=600&fit=crop' },
    ],
  },
  {
    id: 'rex-demo-007',
    type: 'residential_sale',
    property_category: 'Apartment',
    system_status: 'current',
    headline: 'Waterfront Living in Kangaroo Point',
    description: 'Wake up to sweeping river and city views from this premium two-bedroom apartment in the sought-after Rivage complex. Features include stone kitchen, floor-to-ceiling glazing, wide entertaining balcony, and resort amenities including pool, spa, gym, and concierge.',
    property: {
      adr_street_number: '120',
      adr_street_name: 'Main Street',
      adr_suburb_or_town: 'Kangaroo Point',
      adr_state_or_region: 'QLD',
      adr_postcode: '4169',
      adr_unit_number: '1802',
      adr_latitude: -27.4775,
      adr_longitude: 153.0350,
    },
    price_advertise_as: '$785,000',
    price_match: 785000,
    attr_bedrooms: 2,
    attr_bathrooms: 2,
    attr_garages: 1,
    attr_land_area: null,
    attr_land_area_unit: null,
    features: ['Pool', 'Gym', 'Concierge', 'Air Conditioning', 'River Views', 'Secure Parking'],
    images: [
      { uri: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop' },
      { uri: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop' },
    ],
  },
  {
    id: 'rex-demo-008',
    type: 'residential_sale',
    property_category: 'Acreage',
    system_status: 'current',
    headline: 'Private Retreat on 25 Acres with Creek Frontage',
    description: 'An extraordinary lifestyle property offering complete privacy on 25 acres of lush hinterland. The architecturally designed pavilion home features rammed earth walls, solar passive design, and a 15m lap pool. Includes separate studio, horse facilities, and 200m of creek frontage.',
    property: {
      adr_street_number: '88',
      adr_street_name: 'Cedar Creek Road',
      adr_suburb_or_town: 'Tamborine Mountain',
      adr_state_or_region: 'QLD',
      adr_postcode: '4272',
      adr_unit_number: null,
      adr_latitude: -27.9501,
      adr_longitude: 153.1715,
    },
    price_advertise_as: '$2,750,000',
    price_match: 2750000,
    attr_bedrooms: 4,
    attr_bathrooms: 3,
    attr_garages: 4,
    attr_land_area: 101200,
    attr_land_area_unit: 'sqm',
    features: ['Pool', 'Solar', 'Horse Facilities', 'Creek Frontage', 'Separate Studio'],
    images: [
      { uri: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop' },
      { uri: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop' },
    ],
  },
  {
    id: 'rex-demo-009',
    type: 'residential_sale',
    property_category: 'House',
    system_status: 'current',
    headline: 'Beachside Bungalow with Development Potential',
    description: 'Positioned on a generous 680sqm block just 300m from the beach, this charming 3-bedroom bungalow offers fantastic live-in value now with exciting future potential (STCA). North-facing backyard, original timber floors, and a separate rear studio.',
    property: {
      adr_street_number: '14',
      adr_street_name: 'Pacific Avenue',
      adr_suburb_or_town: 'Miami',
      adr_state_or_region: 'QLD',
      adr_postcode: '4220',
      adr_unit_number: null,
      adr_latitude: -28.0672,
      adr_longitude: 153.4395,
    },
    price_advertise_as: '$1,350,000',
    price_match: 1350000,
    attr_bedrooms: 3,
    attr_bathrooms: 1,
    attr_garages: 1,
    attr_land_area: 680,
    attr_land_area_unit: 'sqm',
    features: ['Near Beach', 'Development Potential', 'Rear Studio', 'North-Facing'],
    images: [
      { uri: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop' },
      { uri: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop' },
      { uri: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop' },
    ],
  },
  {
    id: 'rex-demo-010',
    type: 'residential_sale',
    property_category: 'Apartment',
    system_status: 'current',
    headline: 'Boutique Apartment in South Yarra Village',
    description: 'Nestled in a boutique block of just eight, this stylish one-bedroom apartment offers effortless inner-city living. Open-plan layout with timber floors, stone kitchen, European laundry, and a sun-drenched north-facing balcony. Walk to Chapel Street and Toorak Road.',
    property: {
      adr_street_number: '4',
      adr_street_name: 'Chambers Street',
      adr_suburb_or_town: 'South Yarra',
      adr_state_or_region: 'VIC',
      adr_postcode: '3141',
      adr_unit_number: '3',
      adr_latitude: -37.8439,
      adr_longitude: 145.0033,
    },
    price_advertise_as: '$530,000',
    price_match: 530000,
    attr_bedrooms: 1,
    attr_bathrooms: 1,
    attr_garages: 0,
    attr_land_area: null,
    attr_land_area_unit: null,
    features: ['Air Conditioning', 'Intercom', 'North-Facing Balcony'],
    images: [
      { uri: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop' },
      { uri: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop' },
    ],
  },
  {
    id: 'rex-demo-011',
    type: 'residential_sale',
    property_category: 'Townhouse',
    system_status: 'current',
    headline: 'Brand New Luxury Townhome in Robina',
    description: 'Just completed, this impressive three-level townhome features premium finishes at every turn. Chef\'s kitchen with waterfall island, engineered oak floors, ducted air conditioning, private rooftop terrace, and double lock-up garage. Minutes to Robina Town Centre.',
    property: {
      adr_street_number: '7',
      adr_street_name: 'Botticelli Street',
      adr_suburb_or_town: 'Robina',
      adr_state_or_region: 'QLD',
      adr_postcode: '4226',
      adr_unit_number: null,
      adr_latitude: -28.0779,
      adr_longitude: 153.3852,
    },
    price_advertise_as: '$1,080,000',
    price_match: 1080000,
    attr_bedrooms: 4,
    attr_bathrooms: 3,
    attr_garages: 2,
    attr_land_area: 200,
    attr_land_area_unit: 'sqm',
    features: ['Air Conditioning', 'Double Garage', 'Rooftop Terrace', 'New Build'],
    images: [
      { uri: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop' },
      { uri: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop' },
    ],
  },
  {
    id: 'rex-demo-012',
    type: 'residential_sale',
    property_category: 'House',
    system_status: 'current',
    headline: 'Art Deco Classic in Leafy Malvern',
    description: 'A beautifully preserved Art Deco home on one of Malvern\'s finest tree-lined streets. Original leadlight windows, decorative cornices, and arched hallways blend seamlessly with a modern rear extension featuring bi-fold doors to a landscaped garden.',
    property: {
      adr_street_number: '45',
      adr_street_name: 'Stanhope Street',
      adr_suburb_or_town: 'Malvern',
      adr_state_or_region: 'VIC',
      adr_postcode: '3144',
      adr_unit_number: null,
      adr_latitude: -37.8601,
      adr_longitude: 145.0297,
    },
    price_advertise_as: '$3,200,000',
    price_match: 3200000,
    attr_bedrooms: 4,
    attr_bathrooms: 2,
    attr_garages: 2,
    attr_land_area: 650,
    attr_land_area_unit: 'sqm',
    features: ['Air Conditioning', 'Double Garage', 'Garden', 'Period Features'],
    images: [
      { uri: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=600&fit=crop' },
      { uri: 'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800&h=600&fit=crop' },
    ],
  },
];

export const DEMO_OFFICES = [
  { id: 'rex-office-1', name: 'Rex Demo Agency -- Gold Coast', address: '42 Tedder Avenue, Main Beach QLD 4217' },
  { id: 'rex-office-2', name: 'Rex Demo Agency -- Melbourne', address: '120 Collins Street, Melbourne VIC 3000' },
];
